# Generated by Django 4.1.5 on 2024-03-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aluno.aluno')),
                ('plus', models.CharField(max_length=100)),
            ],
            bases=('aluno.aluno',),
        ),
    ]
